import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
type Post = {
  id: string;
  content: string;
  authorId: string;
  createdAt: Date;
};
export default function Home() {
  const { data: allPosts, isLoading } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container">
          {isLoading ? (
            <div>Loading...</div>
          ) : (
            allPosts?.map((post: Post) => (
              <div key={post.id} className="mb-4 rounded bg-white p-4 shadow">
                {post.content}
              </div>
            ))
          )}
        </div>
      </main>
    </>
  );
}
